[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"
[tool.aerich]
tortoise_orm = "src.trial.settings.tortoise_orm"
location = "./migrations"
src_folder = "./."
